services:
  university_service:
    build: ./university_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      PYTHONPATH: ${PYTHONPATH}
      DATABASE_URI: ${DATABASE_URI}
      STUDENT_SERVICE_URL: ${STUDENT_SERVICE_URL}
      GROUP_SERVICE_URL: ${GROUP_SERVICE_URL}
    volumes:
      - ./university_service/:/app/
      - ./common:/app/common
    ports:
      - 8000:8000

  student_service:
    build: ./student_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      PYTHONPATH: ${PYTHONPATH}
      DATABASE_URI: ${DATABASE_URI}
      GROUP_SERVICE_URL: ${GROUP_SERVICE_URL}
    volumes:
      - ./student_service/:/app/
      - ./common:/app/common
    ports:
      - 8001:8000

  group_service:
    build: ./group_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      PYTHONPATH: ${PYTHONPATH}
      DATABASE_URI: ${DATABASE_URI}
      STUDENT_SERVICE_URL: ${STUDENT_SERVICE_URL}
    volumes:
      - ./group_service/:/app/
      - ./common:/app/common
    ports:
      - 8002:8000
  
  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: